linters:
  enable-all: true
  disable:
    - err113
    - gofumpt # Prefer `gofmt` rules / some rules conflict with `wsl`
    # Deprecated linters, removes warning when running
    - execinquery
    - gomnd
linters-settings:
  lll:
    line-length: 130
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(github.com/MarioCarrion/grpc-microservice-example)
    section-separators:
      - newLine
