name: Lint
on: push
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        run: make lint
