name: Lint

on: push

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=3m -v
